Unifik\SystemBundle\Entity\SectionNavigation:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    ordering:
      type: integer
      nullable: true
  manyToOne:
    section:
      targetEntity: Unifik\SystemBundle\Entity\Section
      inversedBy:  sectionNavigations
      joinColumn:
        name: section_id
        referencedColumnName: id
        onDelete:  cascade
    navigation:
      targetEntity: Unifik\SystemBundle\Entity\Navigation
      inversedBy:  sectionNavigations
      joinColumn:
        name: navigation_id
        referencedColumnName: id
        onDelete:  cascade
  uniqueConstraints:
    section_navigation:
      columns: [ section_id, navigation_id ]
