parameters:

    unifik_system.kernel_controller_listener.class:             Unifik\SystemBundle\Listener\ControllerListener
    unifik_system.kernel_response_listener.class:               Unifik\SystemBundle\Listener\ResponseListener
    unifik_system.post_load_listener.class:                     Unifik\SystemBundle\Listener\PostLoadListener
    unifik_system.kernel_exception_listener.class:              Unifik\SystemBundle\Listener\ExceptionListener
    unifik_system.core.class:                                   Unifik\SystemBundle\Lib\Core
    unifik_system.twig_extension.class:                         Unifik\SystemBundle\Extensions\TwigExtension
    unifik_system.twig_translation_extension.class:             Unifik\SystemBundle\Extensions\TranslationExtension
    unifik_system.inspect_extension.class:                      Unifik\SystemBundle\Extensions\InspectExtension
    unifik_system.navigation_builder.class:                     Unifik\SystemBundle\Lib\NavigationBuilder
    unifik_system.navigation_item.class:                        Unifik\SystemBundle\Lib\NavigationItem
    unifik_system.breadcrumbs.class:                            Unifik\SystemBundle\Lib\Breadcrumbs
    unifik_system.page_title.class:                             Unifik\SystemBundle\Lib\PageTitle
    unifik_system.router_invalidator.class:                     Unifik\SystemBundle\Lib\RouterInvalidator
    unifik_system.router_auto_parameters_handler.class:         Unifik\SystemBundle\Lib\RouterAutoParametersHandler
    unifik_system.section_filter.class:                         Unifik\SystemBundle\Lib\SectionFilter
    unifik_system.tree_entity_orderer.class:                    Unifik\SystemBundle\Lib\TreeEntityOrderer
    unifik_system.form.type.tree_choice.class:                  Unifik\SystemBundle\Form\Type\TreeChoiceType
    unifik_system.deletable.class:                              Unifik\SystemBundle\Lib\DeletableService
    unifik_system.deletable_user_listener.class:                Unifik\SystemBundle\Listener\UserDeletableListener
    unifik_system.deletable_role_listener.class:                Unifik\SystemBundle\Listener\RoleDeletableListener
    unifik_system.deletable_section_listener.class:             Unifik\SystemBundle\Listener\SectionDeletableListener
    unifik_system.deletable_app_listener.class:                 Unifik\SystemBundle\Listener\AppDeletableListener
    unifik_system.locale_switcher.class:                        Unifik\SystemBundle\Lib\LocaleSwitcher
    unifik_system.section_translation.sluggable.listener.class: Unifik\SystemBundle\Lib\SectionTranslationSluggableListener
    unifik_system.form.type.creatable_entity.class:             Unifik\SystemBundle\Form\Type\CreatableEntityType
    unifik_backend.security.cms_voter.class:                    Unifik\SystemBundle\Lib\Backend\CmsVoter
    unifik_backend.core.class:                                  Unifik\SystemBundle\Lib\Backend\Core
    unifik_backend.form.type.advanced_file.class:               Unifik\SystemBundle\Form\Backend\AdvancedFileType
    unifik_backend.form.type.advanced_image.class:              Unifik\SystemBundle\Form\Backend\AdvancedImageType
    unifik_backend.login_listener.class:                        Unifik\SystemBundle\Listener\LoginBackendListener
    unifik_frontend.core.class:                                 Unifik\SystemBundle\Lib\Frontend\Core
    unifik_system.translation_editor_loader.class:              Unifik\SystemBundle\Translation\TranslationEditorLoader
    unifik_system.twig.application_context_extension.class:     Unifik\SystemBundle\Extensions\ApplicationContextExtension
    unifik_system.twig.application_path_extension.class:        Unifik\SystemBundle\Extensions\ApplicationPathExtension

services:

    unifik_system.deletable:
        class: %unifik_system.deletable.class%

    egazkt_system.deletable_user_listener:
        class: %unifik_system.deletable_user_listener.class%
        arguments: [ @security.context ]
        tags:
          - { name: unifik_system.deletable, entity: Unifik\SystemBundle\Entity\User }

    egazkt_system.deletable_role_listener:
        class: %unifik_system.deletable_role_listener.class%
        tags:
          - { name: unifik_system.deletable, entity: Unifik\SystemBundle\Entity\Role }

    egazkt_system.deletable_section_listener:
        class: %unifik_system.deletable_section_listener.class%
        tags:
          - { name: unifik_system.deletable, entity: Unifik\SystemBundle\Entity\Section }

    egazkt_system.deletable_app_listener:
        class: %unifik_system.deletable_app_listener.class%
        tags:
          - { name: unifik_system.deletable, entity: Unifik\SystemBundle\Entity\App }

    unifik_system.kernel_controller_listener:
        class: %unifik_system.kernel_controller_listener.class%
        tags:
          - { name: kernel.event_listener, event: kernel.controller }
        calls:
          - [ setContainer, [ @service_container ] ]

    unifik_system.post_load_listener:
        class: %unifik_system.post_load_listener.class%
        tags:
            - { name: doctrine.event_listener, event: postLoad }
        calls:
          - [ setContainer, [ @service_container ] ]

    unifik_system.kernel_exception_listener:
        class: %unifik_system.kernel_exception_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        calls:
            - [ setKernel, [ @kernel ] ]
            - [ setTemplating, [ @templating ] ]
            - [ setTranslator, [ @translator ] ]
            - [ setEntityManager, [ @doctrine.orm.default_entity_manager] ]
            - [ setRequest, [ @?request= ] ]
            - [ setCore, [ @unifik_frontend.core ] ]
            - [ setDefaultLocale, [%locale%] ]

    unifik_system.core:
        class: %unifik_system.core.class%

    unifik_system.twig_extension:
        class: %unifik_system.twig_extension.class%
        tags:
          - { name: twig.extension }
        calls:
          - [ setRequest, [ @?request= ] ]
          - [ setLocale, [ %locale% ] ]
          - [ setSystemCore, [ @unifik_system.core ] ]
          - [ setControllerNameConverter, [ @controller_name_converter ] ]

    unifik_system.twig_translation_extension:
        class: %unifik_system.twig_translation_extension.class%
        tags:
          - { name: twig.extension }
        calls:
          - [ setDoctrine, [ @doctrine ] ]

    unifik_system.inspect_extension:
        class: %unifik_system.inspect_extension.class%
        tags:
          - { name: twig.extension }

    unifik_system.navigation_builder:
        scope: prototype
        class: %unifik_system.navigation_builder.class%
        calls:
          - [ setContainer, [ @service_container ] ]

    unifik_system.navigation_item:
        scope: prototype
        class: %unifik_system.navigation_item.class%

    unifik_system.breadcrumbs:
        shared: true
        class:  %unifik_system.breadcrumbs.class%

    unifik_system.page_title:
        shared: true
        class:  %unifik_system.page_title.class%

    unifik_system.pre_persist_listener:
        class: Unifik\SystemBundle\Listener\DoctrineEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    unifik_system.router_invalidator:
        class: %unifik_system.router_invalidator.class%
        arguments: [ @kernel ]

    unifik_system.router_auto_parameters_handler:
        class: %unifik_system.router_auto_parameters_handler.class%
        calls:
          - [ setContainer, [ @service_container ] ]

    unifik_system.locale_switcher:
        class: %unifik_system.locale_switcher.class%
        arguments: [@service_container]

    unifik_system.form.type.creatable_entity:
        class: %unifik_system.form.type.creatable_entity.class%
        tags:
            - { name: form.type, alias: creatable_entity }

    unifik_backend.core:
        class:  %unifik_backend.core.class%
        shared: true
        calls:
          - [ setContainer, [ @service_container ] ] # only used to fix the request scope widening problem
          - [ setSession, [ @session= ] ]
          - [ setDoctrine, [ @doctrine ] ]
          - [ setBreadcrumbs, [ @unifik_system.breadcrumbs ] ]
          - [ setPageTitle, [ @unifik_system.page_title ] ]
          - [ setLocale, [ %locale% ] ]

    unifik_backend.login_listener:
        class: %unifik_backend.login_listener.class%
        arguments: ['@security.context', '@doctrine', '@router']
        tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    unifik_system.form.type.advanced_file:
        class: %unifik_backend.form.type.advanced_file.class%
        tags:
          - { name: form.type, alias: advanced_file }

    unifik_system.form.type.advanced_image:
        class: %unifik_backend.form.type.advanced_image.class%
        tags:
          - { name: form.type, alias: advanced_image }

    unifik_frontend.core:
        class:  %unifik_frontend.core.class%
        shared: true
        calls:
          - [ setContainer, [ @service_container ] ] # only used to fix the request scope widening problem
          - [ setDoctrine, [ @doctrine ] ]
          - [ setBreadcrumbs, [ @unifik_system.breadcrumbs ] ]
          - [ setPageTitle, [ @unifik_system.page_title ] ]
          
    unifik_system.tree_entity_orderer:
        class: %unifik_system.tree_entity_orderer.class%

    unifik_system.form.type.tree_choice:
        class: %unifik_system.form.type.tree_choice.class%
        arguments: [@unifik_system.tree_entity_orderer]
        tags:
            - { name: form.type, alias: tree_choice }

    unifik_system.section_filter:
        class: %unifik_system.section_filter.class%
        arguments: [@doctrine.orm.entity_manager, @security.context]

    unifik_system.security.cms_voter:
        class: %unifik_backend.security.cms_voter.class%
        arguments: [@service_container]
        tags:
            - { name: security.voter }

    unifik_system.section_translation.sluggable.listener:
        class: %unifik_system.section_translation.sluggable.listener.class%
        tags:
            - { name: doctrine.event_subscriber, type: sluggable, entity: Unifik\SystemBundle\Entity\SectionTranslation }

    unifik_system.translation.translator_editor_loader:
        class: %unifik_system.translation_editor_loader.class%
        arguments: [@doctrine.orm.entity_manager, %kernel.root_dir%]
        tags:
            - { name: translation.loader, alias: db }

    unifik_system.twig.application_context_extension:
        class: %unifik_system.twig.application_context_extension.class%
        synchronized: true
        tags:
          - { name: 'twig.extension' }
        calls:
          - [setControllerNameConverter, [@controller_name_converter]]
          - [setRequest, [@?request=]]

    unifik_system.twig.application_path_extension:
        class: %unifik_system.twig.application_path_extension.class%
        synchronized: true
        tags:
          - { name: 'twig.extension' }
        calls:
          - [ setDoctrine, [ @doctrine ] ]
          - [ setAutoParametersHandler, [ @unifik_system.router_auto_parameters_handler ] ]
          - [ setRouter, [ @router ] ]
          - [ setSystemCore, [ @unifik_system.core ] ]